FROM csprock/dockerfiles:python-data-science-latest

# update ca certificates 
RUN apt-get update && apt-get install -y ca-certificates

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt && rm requirements.txt